[package]
name = "bldr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
curl = "0.4.46"
sysinfo = "0.30.5"
which = "6.0.0"
whoami = "1.4.1"
